/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as ActualizarPasswordRouteImport } from './routes/actualizar-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppUsuariosRouteImport } from './routes/app.usuarios'
import { Route as AppResolucionesRouteImport } from './routes/app.resoluciones'
import { Route as AppNotasRouteImport } from './routes/app.notas'
import { Route as AppMisCursosRouteImport } from './routes/app.mis-cursos'
import { Route as AppLogRouteImport } from './routes/app.log'
import { Route as AppIntervencionesRouteImport } from './routes/app.intervenciones'
import { Route as AppInformesRouteImport } from './routes/app.informes'
import { Route as AppCoordinacionRouteImport } from './routes/app.coordinacion'
import { Route as AppControlClasesRouteImport } from './routes/app.control-clases'
import { Route as AppConfiguracionRouteImport } from './routes/app.configuracion'
import { Route as AppComunicacionRouteImport } from './routes/app.comunicacion'
import { Route as AppAsistenciaRouteImport } from './routes/app.asistencia'
import { Route as AppAnotacionesRouteImport } from './routes/app.anotaciones'
import { Route as AppAlumnosPieRouteImport } from './routes/app.alumnos-pie'
import { Route as AppAlumnosRouteImport } from './routes/app.alumnos'
import { Route as AppAlertasRouteImport } from './routes/app.alertas'
import { Route as AppAlumnosIndexRouteImport } from './routes/app.alumnos.index'
import { Route as AppConfiguracionAsignarRouteImport } from './routes/app.configuracion.asignar'
import { Route as AppAlumnosIdRouteImport } from './routes/app.alumnos.$id'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualizarPasswordRoute = ActualizarPasswordRouteImport.update({
  id: '/actualizar-password',
  path: '/actualizar-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppResolucionesRoute = AppResolucionesRouteImport.update({
  id: '/resoluciones',
  path: '/resoluciones',
  getParentRoute: () => AppRoute,
} as any)
const AppNotasRoute = AppNotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => AppRoute,
} as any)
const AppMisCursosRoute = AppMisCursosRouteImport.update({
  id: '/mis-cursos',
  path: '/mis-cursos',
  getParentRoute: () => AppRoute,
} as any)
const AppLogRoute = AppLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AppRoute,
} as any)
const AppIntervencionesRoute = AppIntervencionesRouteImport.update({
  id: '/intervenciones',
  path: '/intervenciones',
  getParentRoute: () => AppRoute,
} as any)
const AppInformesRoute = AppInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AppRoute,
} as any)
const AppCoordinacionRoute = AppCoordinacionRouteImport.update({
  id: '/coordinacion',
  path: '/coordinacion',
  getParentRoute: () => AppRoute,
} as any)
const AppControlClasesRoute = AppControlClasesRouteImport.update({
  id: '/control-clases',
  path: '/control-clases',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppComunicacionRoute = AppComunicacionRouteImport.update({
  id: '/comunicacion',
  path: '/comunicacion',
  getParentRoute: () => AppRoute,
} as any)
const AppAsistenciaRoute = AppAsistenciaRouteImport.update({
  id: '/asistencia',
  path: '/asistencia',
  getParentRoute: () => AppRoute,
} as any)
const AppAnotacionesRoute = AppAnotacionesRouteImport.update({
  id: '/anotaciones',
  path: '/anotaciones',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumnosPieRoute = AppAlumnosPieRouteImport.update({
  id: '/alumnos-pie',
  path: '/alumnos-pie',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumnosRoute = AppAlumnosRouteImport.update({
  id: '/alumnos',
  path: '/alumnos',
  getParentRoute: () => AppRoute,
} as any)
const AppAlertasRoute = AppAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AppRoute,
} as any)
const AppAlumnosIndexRoute = AppAlumnosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAlumnosRoute,
} as any)
const AppConfiguracionAsignarRoute = AppConfiguracionAsignarRouteImport.update({
  id: '/asignar',
  path: '/asignar',
  getParentRoute: () => AppConfiguracionRoute,
} as any)
const AppAlumnosIdRoute = AppAlumnosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppAlumnosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualizar-password': typeof ActualizarPasswordRoute
  '/app': typeof AppRouteWithChildren
  '/app/alertas': typeof AppAlertasRoute
  '/app/alumnos': typeof AppAlumnosRouteWithChildren
  '/app/alumnos-pie': typeof AppAlumnosPieRoute
  '/app/anotaciones': typeof AppAnotacionesRoute
  '/app/asistencia': typeof AppAsistenciaRoute
  '/app/comunicacion': typeof AppComunicacionRoute
  '/app/configuracion': typeof AppConfiguracionRouteWithChildren
  '/app/control-clases': typeof AppControlClasesRoute
  '/app/coordinacion': typeof AppCoordinacionRoute
  '/app/informes': typeof AppInformesRoute
  '/app/intervenciones': typeof AppIntervencionesRoute
  '/app/log': typeof AppLogRoute
  '/app/mis-cursos': typeof AppMisCursosRoute
  '/app/notas': typeof AppNotasRoute
  '/app/resoluciones': typeof AppResolucionesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/alumnos/$id': typeof AppAlumnosIdRoute
  '/app/configuracion/asignar': typeof AppConfiguracionAsignarRoute
  '/app/alumnos/': typeof AppAlumnosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualizar-password': typeof ActualizarPasswordRoute
  '/app/alertas': typeof AppAlertasRoute
  '/app/alumnos-pie': typeof AppAlumnosPieRoute
  '/app/anotaciones': typeof AppAnotacionesRoute
  '/app/asistencia': typeof AppAsistenciaRoute
  '/app/comunicacion': typeof AppComunicacionRoute
  '/app/configuracion': typeof AppConfiguracionRouteWithChildren
  '/app/control-clases': typeof AppControlClasesRoute
  '/app/coordinacion': typeof AppCoordinacionRoute
  '/app/informes': typeof AppInformesRoute
  '/app/intervenciones': typeof AppIntervencionesRoute
  '/app/log': typeof AppLogRoute
  '/app/mis-cursos': typeof AppMisCursosRoute
  '/app/notas': typeof AppNotasRoute
  '/app/resoluciones': typeof AppResolucionesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app': typeof AppIndexRoute
  '/app/alumnos/$id': typeof AppAlumnosIdRoute
  '/app/configuracion/asignar': typeof AppConfiguracionAsignarRoute
  '/app/alumnos': typeof AppAlumnosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualizar-password': typeof ActualizarPasswordRoute
  '/app': typeof AppRouteWithChildren
  '/app/alertas': typeof AppAlertasRoute
  '/app/alumnos': typeof AppAlumnosRouteWithChildren
  '/app/alumnos-pie': typeof AppAlumnosPieRoute
  '/app/anotaciones': typeof AppAnotacionesRoute
  '/app/asistencia': typeof AppAsistenciaRoute
  '/app/comunicacion': typeof AppComunicacionRoute
  '/app/configuracion': typeof AppConfiguracionRouteWithChildren
  '/app/control-clases': typeof AppControlClasesRoute
  '/app/coordinacion': typeof AppCoordinacionRoute
  '/app/informes': typeof AppInformesRoute
  '/app/intervenciones': typeof AppIntervencionesRoute
  '/app/log': typeof AppLogRoute
  '/app/mis-cursos': typeof AppMisCursosRoute
  '/app/notas': typeof AppNotasRoute
  '/app/resoluciones': typeof AppResolucionesRoute
  '/app/usuarios': typeof AppUsuariosRoute
  '/app/': typeof AppIndexRoute
  '/app/alumnos/$id': typeof AppAlumnosIdRoute
  '/app/configuracion/asignar': typeof AppConfiguracionAsignarRoute
  '/app/alumnos/': typeof AppAlumnosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualizar-password'
    | '/app'
    | '/app/alertas'
    | '/app/alumnos'
    | '/app/alumnos-pie'
    | '/app/anotaciones'
    | '/app/asistencia'
    | '/app/comunicacion'
    | '/app/configuracion'
    | '/app/control-clases'
    | '/app/coordinacion'
    | '/app/informes'
    | '/app/intervenciones'
    | '/app/log'
    | '/app/mis-cursos'
    | '/app/notas'
    | '/app/resoluciones'
    | '/app/usuarios'
    | '/app/'
    | '/app/alumnos/$id'
    | '/app/configuracion/asignar'
    | '/app/alumnos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualizar-password'
    | '/app/alertas'
    | '/app/alumnos-pie'
    | '/app/anotaciones'
    | '/app/asistencia'
    | '/app/comunicacion'
    | '/app/configuracion'
    | '/app/control-clases'
    | '/app/coordinacion'
    | '/app/informes'
    | '/app/intervenciones'
    | '/app/log'
    | '/app/mis-cursos'
    | '/app/notas'
    | '/app/resoluciones'
    | '/app/usuarios'
    | '/app'
    | '/app/alumnos/$id'
    | '/app/configuracion/asignar'
    | '/app/alumnos'
  id:
    | '__root__'
    | '/'
    | '/actualizar-password'
    | '/app'
    | '/app/alertas'
    | '/app/alumnos'
    | '/app/alumnos-pie'
    | '/app/anotaciones'
    | '/app/asistencia'
    | '/app/comunicacion'
    | '/app/configuracion'
    | '/app/control-clases'
    | '/app/coordinacion'
    | '/app/informes'
    | '/app/intervenciones'
    | '/app/log'
    | '/app/mis-cursos'
    | '/app/notas'
    | '/app/resoluciones'
    | '/app/usuarios'
    | '/app/'
    | '/app/alumnos/$id'
    | '/app/configuracion/asignar'
    | '/app/alumnos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualizarPasswordRoute: typeof ActualizarPasswordRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualizar-password': {
      id: '/actualizar-password'
      path: '/actualizar-password'
      fullPath: '/actualizar-password'
      preLoaderRoute: typeof ActualizarPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usuarios': {
      id: '/app/usuarios'
      path: '/usuarios'
      fullPath: '/app/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resoluciones': {
      id: '/app/resoluciones'
      path: '/resoluciones'
      fullPath: '/app/resoluciones'
      preLoaderRoute: typeof AppResolucionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notas': {
      id: '/app/notas'
      path: '/notas'
      fullPath: '/app/notas'
      preLoaderRoute: typeof AppNotasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/mis-cursos': {
      id: '/app/mis-cursos'
      path: '/mis-cursos'
      fullPath: '/app/mis-cursos'
      preLoaderRoute: typeof AppMisCursosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/log': {
      id: '/app/log'
      path: '/log'
      fullPath: '/app/log'
      preLoaderRoute: typeof AppLogRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/intervenciones': {
      id: '/app/intervenciones'
      path: '/intervenciones'
      fullPath: '/app/intervenciones'
      preLoaderRoute: typeof AppIntervencionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/informes': {
      id: '/app/informes'
      path: '/informes'
      fullPath: '/app/informes'
      preLoaderRoute: typeof AppInformesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coordinacion': {
      id: '/app/coordinacion'
      path: '/coordinacion'
      fullPath: '/app/coordinacion'
      preLoaderRoute: typeof AppCoordinacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/control-clases': {
      id: '/app/control-clases'
      path: '/control-clases'
      fullPath: '/app/control-clases'
      preLoaderRoute: typeof AppControlClasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracion': {
      id: '/app/configuracion'
      path: '/configuracion'
      fullPath: '/app/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/comunicacion': {
      id: '/app/comunicacion'
      path: '/comunicacion'
      fullPath: '/app/comunicacion'
      preLoaderRoute: typeof AppComunicacionRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/asistencia': {
      id: '/app/asistencia'
      path: '/asistencia'
      fullPath: '/app/asistencia'
      preLoaderRoute: typeof AppAsistenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/anotaciones': {
      id: '/app/anotaciones'
      path: '/anotaciones'
      fullPath: '/app/anotaciones'
      preLoaderRoute: typeof AppAnotacionesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alumnos-pie': {
      id: '/app/alumnos-pie'
      path: '/alumnos-pie'
      fullPath: '/app/alumnos-pie'
      preLoaderRoute: typeof AppAlumnosPieRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alumnos': {
      id: '/app/alumnos'
      path: '/alumnos'
      fullPath: '/app/alumnos'
      preLoaderRoute: typeof AppAlumnosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alertas': {
      id: '/app/alertas'
      path: '/alertas'
      fullPath: '/app/alertas'
      preLoaderRoute: typeof AppAlertasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/alumnos/': {
      id: '/app/alumnos/'
      path: '/'
      fullPath: '/app/alumnos/'
      preLoaderRoute: typeof AppAlumnosIndexRouteImport
      parentRoute: typeof AppAlumnosRoute
    }
    '/app/configuracion/asignar': {
      id: '/app/configuracion/asignar'
      path: '/asignar'
      fullPath: '/app/configuracion/asignar'
      preLoaderRoute: typeof AppConfiguracionAsignarRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/app/alumnos/$id': {
      id: '/app/alumnos/$id'
      path: '/$id'
      fullPath: '/app/alumnos/$id'
      preLoaderRoute: typeof AppAlumnosIdRouteImport
      parentRoute: typeof AppAlumnosRoute
    }
  }
}

interface AppAlumnosRouteChildren {
  AppAlumnosIdRoute: typeof AppAlumnosIdRoute
  AppAlumnosIndexRoute: typeof AppAlumnosIndexRoute
}

const AppAlumnosRouteChildren: AppAlumnosRouteChildren = {
  AppAlumnosIdRoute: AppAlumnosIdRoute,
  AppAlumnosIndexRoute: AppAlumnosIndexRoute,
}

const AppAlumnosRouteWithChildren = AppAlumnosRoute._addFileChildren(
  AppAlumnosRouteChildren,
)

interface AppConfiguracionRouteChildren {
  AppConfiguracionAsignarRoute: typeof AppConfiguracionAsignarRoute
}

const AppConfiguracionRouteChildren: AppConfiguracionRouteChildren = {
  AppConfiguracionAsignarRoute: AppConfiguracionAsignarRoute,
}

const AppConfiguracionRouteWithChildren =
  AppConfiguracionRoute._addFileChildren(AppConfiguracionRouteChildren)

interface AppRouteChildren {
  AppAlertasRoute: typeof AppAlertasRoute
  AppAlumnosRoute: typeof AppAlumnosRouteWithChildren
  AppAlumnosPieRoute: typeof AppAlumnosPieRoute
  AppAnotacionesRoute: typeof AppAnotacionesRoute
  AppAsistenciaRoute: typeof AppAsistenciaRoute
  AppComunicacionRoute: typeof AppComunicacionRoute
  AppConfiguracionRoute: typeof AppConfiguracionRouteWithChildren
  AppControlClasesRoute: typeof AppControlClasesRoute
  AppCoordinacionRoute: typeof AppCoordinacionRoute
  AppInformesRoute: typeof AppInformesRoute
  AppIntervencionesRoute: typeof AppIntervencionesRoute
  AppLogRoute: typeof AppLogRoute
  AppMisCursosRoute: typeof AppMisCursosRoute
  AppNotasRoute: typeof AppNotasRoute
  AppResolucionesRoute: typeof AppResolucionesRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAlertasRoute: AppAlertasRoute,
  AppAlumnosRoute: AppAlumnosRouteWithChildren,
  AppAlumnosPieRoute: AppAlumnosPieRoute,
  AppAnotacionesRoute: AppAnotacionesRoute,
  AppAsistenciaRoute: AppAsistenciaRoute,
  AppComunicacionRoute: AppComunicacionRoute,
  AppConfiguracionRoute: AppConfiguracionRouteWithChildren,
  AppControlClasesRoute: AppControlClasesRoute,
  AppCoordinacionRoute: AppCoordinacionRoute,
  AppInformesRoute: AppInformesRoute,
  AppIntervencionesRoute: AppIntervencionesRoute,
  AppLogRoute: AppLogRoute,
  AppMisCursosRoute: AppMisCursosRoute,
  AppNotasRoute: AppNotasRoute,
  AppResolucionesRoute: AppResolucionesRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualizarPasswordRoute: ActualizarPasswordRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
